# Neo4j Graph Analyzer Configuration
# Example configurations for different databases

databases:
  local:
    uri: "bolt://localhost:7687"
    username: "neo4j"
    password: "password"
    database: "neo4j"
  
  fraud_analysis:
    uri: "bolt://localhost:7687"
    username: "neo4j"
    password: "password"
    database: "fraud_db"
  
  production:
    uri: "bolt://prod-server:7687"
    username: "neo4j"
    password: "secure_password"
    database: "production"

# Default settings
defaults:
  max_depth: 4
  output_format: "table"
  export_file: "graph_analysis.json"
